variables:
  OSDU_GCP_SERVICE: dataset
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: dataset
  OSDU_GCP_TEST_SUBDIR: testing/$OSDU_GCP_SERVICE-test-$OSDU_GCP_VENDOR
  OSDU_GCP_HELM_PACKAGE_CHARTS: "devops/gcp/deploy devops/gcp/configmap"
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS: >
    --set data.googleAudiences=$GOOGLE_AUDIENCE
    --set data.redisGroupHost=$REDIS_GROUP_HOST
  OSDU_GCP_HELM_CONFIG_SERVICE_VARS_DEV2: >
    --set data.googleAudiences=$GOOGLE_AUDIENCE
    --set data.redisGroupHost=$REDIS_GROUP_HOST
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: >
    --set data.image=$CI_REGISTRY_IMAGE/osdu-gcp-$OSDU_GCP_SERVICE:$CI_COMMIT_SHORT_SHA
    --set data.serviceAccountName=$OSDU_GCP_SERVICE-k8s
  OSDU_GCP_HELM_CONFIG_SERVICE: dataset-config
  OSDU_GCP_HELM_DEPLOYMENT_SERVICE: dataset-deploy

osdu-gcp-test:
  variables:
    STORAGE_BASE_URL: $OSDU_GCP_STORAGE_EXTERNAL_URL
    LEGAL_BASE_URL: $OSDU_GCP_LEGAL_EXTERNAL_URL
    DATASET_BASE_URL: $OSDU_GCP_DATASET_EXTERNAL_URL
    SCHEMA_API: $OSDU_GCP_SCHEMA_URL
    PROVIDER_KEY: GCP
    KIND_SUBTYPE: DatasetTest
    LEGAL_TAG: datatest-int-tag
    LEGAL_HOST: $OSDU_GCP_LEGAL_EXTERNAL_URL
    GCP_STORAGE_PERSISTENT_AREA: persistent-area
    GCP_DEPLOY_FILE: $OSDU_GCP_DEPLOY_FILE

osdu-gcp-dev2-test:
  variables:
    STORAGE_BASE_URL: $OSDU_GCP_STORAGE_EXTERNAL_URL
    LEGAL_BASE_URL: $OSDU_GCP_LEGAL_EXTERNAL_URL
    DATASET_BASE_URL: $OSDU_GCP_DATASET_EXTERNAL_URL
    SCHEMA_API: $OSDU_GCP_SCHEMA_URL
    PROVIDER_KEY: GCP
    KIND_SUBTYPE: DatasetTest
    LEGAL_TAG: datatest-int-tag
    LEGAL_HOST: $OSDU_GCP_LEGAL_EXTERNAL_URL
    GCP_STORAGE_PERSISTENT_AREA: persistent-area
    GCP_DEPLOY_FILE: $OSDU_GCP_DEPLOY_FILE
