# Copyright © Amazon Web Services
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CloudFormation template for creating the resources used for the sending messages to topic and queues to receive the
  messages for OSDU's delivery service. It creates the SNS Topic and the corresponding SQS Queues with their associated policies.

Parameters:
  Environment:
    Description: an environment name that will be prefixed to resource names.
    Type: String
    AllowedValues:
      - dev
      - uat
      - prod
    ConstraintDescription: Can only be "dev/uat/prod"
    Default: dev

  Region:
    Description: The AWS region to deploy the resources to.
    Type: String
    Default: us-east-1

  SNSTopicName:
    Description: >-
      The name of the Simple Notification Service topic for the OS Delivery Service. Defaults to osdu-delivery-service-messages.
      Will be prefixed with the environment name.
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Default: osdu-delivery-service-messages
    Type: String
    MinLength: '1'
    MaxLength: '64'

  SQSQueueName:
    Description: >-
      The name of the Simple Queue Service queue for the OS Delivery Service. Defaults to osdu-delivery-service-queue.
      Will be prefixed with the environment name.
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Default: osdu-delivery-service-queue
    Type: String
    MinLength: '1'
    MaxLength: '64'

Resources:
  OSDUDeliveryServiceSNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: !Sub ${Environment}-${AWS::AccountId}-${SNSTopicName}
      TopicName: !Sub ${Environment}-${SNSTopicName}

  OSDUDeliveryServiceSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-${AWS::AccountId}-${SQSQueueName}

  OSDUDeliveryServiceSNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref OSDUDeliveryServiceSNSTopic
      RawMessageDelivery: true
      Endpoint: !GetAtt OSDUDeliveryServiceSQSQueue.Arn

  OSDUQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Id: OSDUQueuePolicy
        Statement:
          - Sid: Allow-SendMessage-To-Queues-From-SNS-Topic
            Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
            Resource: "*"
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: OSDUDeliveryServiceSNSTopic
      Queues:
        - Ref: OSDUDeliveryServiceSQSQueue

Outputs:
  OSDUDeliveryServiceSNSTopicTopicName:
    Value: !Sub ${Environment}-${AWS::AccountId}-${SNSTopicName}
    Description: Topic Name of the Delivery Service Message Bus SNS Topic
    Export:
      Name: !Sub ${Environment}-OSDUDeliveryServiceSNSTopic

  OSDUDeliveryServiceSQSQueueName:
    Value: !Sub ${Environment}-${AWS::AccountId}-${SQSQueueName}
    Description: Queue Name of Subscribed Delivery Service Message Bus SQS Queue
    Export:
      Name: !Sub ${Environment}-OSDUDeliveryServiceSQSQueue
