apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Values.conf.app_name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  hosts:
    {{- if .Values.conf.domain }}
    - "{{ .Values.conf.domain }}"
    {{- else }}
    - "*"
    {{- end }}
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            prefix: "/api/dataset"
      route:
        - destination:
            port:
              number: 80
            host: "{{ .Values.conf.app_name }}.{{ .Release.Namespace }}.svc.cluster.local"
